language: node_js
node_js: stable
branches:
  only:
  - blog-source
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name "${GIT_USER_NAME}"
- git config --global user.email "${GIT_USER_EMAIL}"
- sed -i'' "s~git@github.com:${STATIC_SITE_REPO}~https://${ACCESS_TOKEN}:x-oauth-basic@github.com/${STATIC_SITE_REPO}~" _config.yml
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
env:
  global:
    secure: xVHNJsWmKkJZ6xzUGEwj+BQzD494iU2Mi+iWrw1wWD+aVUMY/1Ft5u9mGQ+xnDRAAOjSN+MiotXFbmZYopo9C7FAoNJp2/u6RqGfDLqYUiOiVg56mPebACyE9CSVMzOTyveSqETAFD7nl5vLcddYLe36BK6YhfzSgORuMBguSNgbJul3wdsDviNyDlSlbQRAdkX9YFMX3fgCnJujxxLhAf8Fhu9fepdTPY1h7xKkHAnSkpKpdEMRMXcdv+R177i3/XZI/pNjUZMStTLritfAq5/pXfC48ussFGa/MFReHiM8n8f+YQzzgyc3N1QR8E6Wlm3udjMNP8/2il8AH6kTMacHGRCZ57Xxi3jFBkiep19G52jN0EWsBKmgDY5z1q0qU4m5Oql/UD9gSttOP9X0b85mDeYhqDnkK7dNws3jgTCjoCfsKeAjJu7ESmtLJrCesS/h7JlzRC+ZANr1MrkXpNuySdFDOAsxvHnS/Uc3t87lct+IZ/Id7vc9jKWoVWgWwIu+0ZUatOQ7xwCkPtvNTkPcQlUz2Fw+U7OyLulgasN+7PLCcs/p6J+v4R/7zQBfaEzCJ240WFAhibvsdW1wOhMc29AGe0KhaQ+DZ7HXEc8fIYuToNiBbotv0MYaqwWTdPGy+3CIxXM9bW8rlNGj0nwzlg+r+2tF73pMZOwKog4=
